#pragma once

#define WWDG_IRQHandler             Irq0_Handler
#define PVD_IRQHandler              Irq1_Handler
#define TAMPER_IRQHandler           Irq2_Handler
#define RTC_IRQHandler              Irq3_Handler
#define FLASH_IRQHandler            Irq4_Handler
#define RCC_IRQHandler              Irq5_Handler
#define EXTI0_IRQHandler            Irq6_Handler
#define EXTI1_IRQHandler            Irq7_Handler
#define EXTI2_IRQHandler            Irq8_Handler
#define EXTI3_IRQHandler            Irq9_Handler
#define EXTI4_IRQHandler            Irq10_Handler
#define DMA1_Channel1_IRQHandler    Irq11_Handler
#define DMA1_Channel2_IRQHandler    Irq12_Handler
#define DMA1_Channel3_IRQHandler    Irq13_Handler
#define DMA1_Channel4_IRQHandler    Irq14_Handler
#define DMA1_Channel5_IRQHandler    Irq15_Handler
#define DMA1_Channel6_IRQHandler    Irq16_Handler
#define DMA1_Channel7_IRQHandler    Irq17_Handler
#define ADC1_2_IRQHandler           Irq18_Handler
#define USB_HP_CAN1_TX_IRQHandler   Irq19_Handler
#define USB_LP_CAN1_RX0_IRQHandler  Irq20_Handler
#define CAN1_RX1_IRQHandler         Irq21_Handler
#define CAN1_SCE_IRQHandler         Irq22_Handler
#define EXTI9_5_IRQHandler          Irq23_Handler
#define TIM1_BRK_IRQHandler         Irq24_Handler
#define TIM1_UP_IRQHandler          Irq25_Handler
#define TIM1_TRG_COM_IRQHandler     Irq26_Handler
#define TIM1_CC_IRQHandler          Irq27_Handler
#define TIM2_IRQHandler             Irq28_Handler
#define TIM3_IRQHandler             Irq29_Handler
#define TIM4_IRQHandler             Irq30_Handler
#define I2C1_EV_IRQHandler          Irq31_Handler
#define I2C1_ER_IRQHandler          Irq32_Handler
#define I2C2_EV_IRQHandler          Irq33_Handler
#define I2C2_ER_IRQHandler          Irq34_Handler
#define SPI1_IRQHandler             Irq35_Handler
#define SPI2_IRQHandler             Irq36_Handler
#define USART1_IRQHandler           Irq37_Handler
#define USART2_IRQHandler           Irq38_Handler
#define USART3_IRQHandler           Irq39_Handler
#define EXTI15_10_IRQHandler        Irq40_Handler
#define RTC_Alarm_IRQHandler        Irq41_Handler
#define USBWakeUp_IRQHandler        Irq42_Handler
#define TIM8_BRK_IRQHandler         Irq43_Handler
#define TIM8_UP_IRQHandler          Irq44_Handler
#define TIM8_TRG_COM_IRQHandler     Irq45_Handler
#define TIM8_CC_IRQHandler          Irq46_Handler
#define ADC3_IRQHandler             Irq47_Handler
#define FSMC_IRQHandler             Irq48_Handler
#define SDIO_IRQHandler             Irq49_Handler
#define TIM5_IRQHandler             Irq50_Handler
#define SPI3_IRQHandler             Irq51_Handler
#define UART4_IRQHandler            Irq52_Handler
#define UART5_IRQHandler            Irq53_Handler
#define TIM6_IRQHandler             Irq54_Handler
#define TIM7_IRQHandler             Irq55_Handler
#define DMA2_Channel1_IRQHandler    Irq56_Handler
#define DMA2_Channel2_IRQHandler    Irq57_Handler
#define DMA2_Channel3_IRQHandler    Irq58_Handler
#define DMA2_Channel4_5_IRQHandler  Irq59_Handler
